// Hard-coded snapshot for the public read-only demo at `#/demo`.
//
// Everything MatterDetail consumes is pre-rendered here as plain JSON-shaped
// TypeScript. No backend calls. No skill/plugin substrate is surfaced — the
// solicitor sees the workspace, not the mechanism.
//
// Source material:
//   - backend/app/core/seed.py (Khan v Acme canonical content)

import type {
  AssistantMessage,
  AuditEntry,
  ChronologyResponse,
  Matter,
  MatterDocument,
} from "../lib/api";

export const DEMO_SLUG = "khan-v-acme-trading-2026";

// Stable UUID-shaped strings — the demo never persists, but components key
// off these (audit row id, document id, citation id) and React warns on dupes.
const ID = {
  matter: "11111111-1111-1111-1111-111111111111",
  user: "22222222-2222-2222-2222-222222222222",
  dismissal: "33333333-3333-3333-3333-333333333301",
  witness: "33333333-3333-3333-3333-333333333302",
  nda: "33333333-3333-3333-3333-333333333303",
  reviewCorrespondence: "44444444-4444-4444-4444-444444444401",
  reviewDisclosure: "44444444-4444-4444-4444-444444444402",
  citationBurchell: "55555555-5555-5555-5555-555555555501",
  citationIceland: "55555555-5555-5555-5555-555555555502",
  citationPolkey: "55555555-5555-5555-5555-555555555503",
};

const MATTER: Matter = {
  id: ID.matter,
  slug: DEMO_SLUG,
  title: "Khan v Acme Trading Ltd",
  matter_type: "employment_tribunal",
  cause: "s.94 ERA 1996, unfair dismissal",
  status: "open",
  case_theory:
    "Ms Khan was dismissed by Acme Trading Ltd on 12 March 2026, after three years and four months of continuous service. The stated reason was conduct — a single alleged breach of the company's social-media policy — but the dismissal followed a documented grievance Ms Khan had raised six weeks earlier concerning her line manager's pattern of conduct toward female members of the warehouse team.\n\nOur case is that the conduct reason is pretextual. The real reason for dismissal falls within s.103A ERA 1996 (protected disclosure) or, in the alternative, constitutes victimisation under s.27 Equality Act 2010. The Burchell test fails on the second and third limbs: the investigator was the manager who was the subject of Ms Khan's prior grievance, and the sanction sat outside the band of reasonable responses given a clean disciplinary record and Iceland Frozen Foods proportionality.",
  pivot_fact:
    "The social-media post the respondent treats as gross misconduct was a private comment on a personal Instagram account, set to a closed audience of 47 followers, none of whom were customers, suppliers, or named in the post.",
  privilege_posture: "B_mixed",
  default_model_id: "claude-sonnet-4-6",
  required_provider: "anthropic",
  facts: {
    side: "claimant",
    parties: { client: "Jasmine Khan", opposing: ["Acme Trading Ltd"] },
    computed: { latest_et1: "2026-07-03" },
  },
  opened_at: "2026-04-02T09:14:22Z",
  closed_at: null,
  retention_until: "2032-04-02T00:00:00Z",
  created_by_id: ID.user,
};

const DOCUMENTS: MatterDocument[] = [
  {
    id: ID.dismissal,
    matter_id: ID.matter,
    filename: "khan-dismissal-letter.pdf",
    mime_type: "application/pdf",
    size_bytes: 412_000,
    sha256: "a31cf78d20e94b5e89f4c216de7d8f04a6c5f9b2d4310a7fbb9f4e0d2c5a83e9",
    tag: "disclosure",
    from_disclosure: true,
    uploaded_at: "2026-04-02T09:32:11Z",
    uploaded_by_id: ID.user,
  },
  {
    id: ID.witness,
    matter_id: ID.matter,
    filename: "witness-statement-khan.docx",
    mime_type:
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size_bytes: 128_000,
    sha256: "b7e2d4c9183fa70d5e1b6a93f24e8b0d61eb15bd3f4ad62c8d9e10b7f3a4c512",
    tag: "draft",
    from_disclosure: false,
    uploaded_at: "2026-04-03T15:48:02Z",
    uploaded_by_id: ID.user,
  },
  {
    id: ID.nda,
    matter_id: ID.matter,
    filename: "synthetic-mutual-nda.docx",
    mime_type:
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    size_bytes: 41_280,
    sha256: "c9d3f1b5a8472e0c63a8b2d75ec104f9b1d2a3e6f4c8b9d0e1a2f3b4c5d6e7f8",
    tag: "contract",
    from_disclosure: false,
    uploaded_at: "2026-04-04T11:12:55Z",
    uploaded_by_id: ID.user,
  },
];

// Audit narrates the workspace: open matter → upload docs → build
// chronology → draft LBA → run pre-motion → run contract review → run
// anonymisation. NO plugin/skill detail surfaced.
const AUDIT: AuditEntry[] = [
  {
    id: "audit-01",
    timestamp: "2026-04-02T09:14:22Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "matter.create",
    module: null,
    resource_type: "matter",
    resource_id: ID.matter,
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 32,
    payload: {},
  },
  {
    id: "audit-02",
    timestamp: "2026-04-02T09:32:11Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "document.upload",
    module: null,
    resource_type: "document",
    resource_id: ID.dismissal,
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 184,
    payload: { filename: "khan-dismissal-letter.pdf" },
  },
  {
    id: "audit-03",
    timestamp: "2026-04-02T09:32:42Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "document.extract",
    module: "documents",
    resource_type: "document_body",
    resource_id: ID.dismissal,
    model_used: null,
    prompt_hash: "a1b2c3d4",
    response_hash: "f9e8d7c6",
    token_count: null,
    latency_ms: 612,
    payload: { extraction_method: "pdf-text" },
  },
  {
    id: "audit-04",
    timestamp: "2026-04-03T15:48:02Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "document.upload",
    module: null,
    resource_type: "document",
    resource_id: ID.witness,
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 142,
    payload: { filename: "witness-statement-khan.docx" },
  },
  {
    id: "audit-05",
    timestamp: "2026-04-04T11:12:55Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "document.upload",
    module: null,
    resource_type: "document",
    resource_id: ID.nda,
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 121,
    payload: { filename: "synthetic-mutual-nda.docx" },
  },
  {
    id: "audit-06",
    timestamp: "2026-04-04T13:02:09Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "chronology.build",
    module: "chronology",
    resource_type: "matter",
    resource_id: ID.matter,
    model_used: "claude-opus-4-7",
    prompt_hash: "12ad9f8b",
    response_hash: "0c4e3b71",
    token_count: 4_812,
    latency_ms: 5_104,
    payload: { events: 7 },
  },
  {
    id: "audit-07",
    timestamp: "2026-04-04T13:02:14Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "chronology.gate.confirm",
    module: "chronology",
    resource_type: "matter",
    resource_id: ID.matter,
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 28,
    payload: { acknowledgement: "CPR 31.22 implied undertaking" },
  },
  {
    id: "audit-08",
    timestamp: "2026-04-05T10:14:00Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "case_law.search",
    module: "research",
    resource_type: "matter",
    resource_id: ID.matter,
    model_used: "claude-opus-4-7",
    prompt_hash: "8f1c9bd2",
    response_hash: "32c7a8e1",
    token_count: 1_864,
    latency_ms: 2_983,
    payload: { query: "Burchell unfair dismissal" },
  },
  {
    id: "audit-09",
    timestamp: "2026-04-05T10:16:42Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "citation.create",
    module: "research",
    resource_type: "citation",
    resource_id: ID.citationBurchell,
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 41,
    payload: { case_name: "British Home Stores Ltd v Burchell" },
  },
  {
    id: "audit-10",
    timestamp: "2026-04-05T10:18:11Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "citation.create",
    module: "research",
    resource_type: "citation",
    resource_id: ID.citationIceland,
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 38,
    payload: { case_name: "Iceland Frozen Foods Ltd v Jones" },
  },
  {
    id: "audit-11",
    timestamp: "2026-04-05T10:18:46Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "citation.create",
    module: "research",
    resource_type: "citation",
    resource_id: ID.citationPolkey,
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 35,
    payload: { case_name: "Polkey v A E Dayton Services Ltd" },
  },
  {
    id: "audit-12",
    timestamp: "2026-04-05T14:33:21Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "letter.draft",
    module: "letters",
    resource_type: "letter_draft",
    resource_id: "letter-lba-01",
    model_used: "claude-opus-4-7",
    prompt_hash: "7a4f2d31",
    response_hash: "be3d2c10",
    token_count: 3_512,
    latency_ms: 7_204,
    payload: { letter_type: "lba" },
  },
  {
    id: "audit-13",
    timestamp: "2026-04-05T14:34:09Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "letter.export.docx",
    module: "letters",
    resource_type: "letter_draft",
    resource_id: "letter-lba-01",
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 412,
    payload: { bytes: 28_416 },
  },
  {
    id: "audit-14",
    timestamp: "2026-04-06T09:02:18Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "pre_motion.run",
    module: "pre_motion",
    resource_type: "matter",
    resource_id: ID.matter,
    model_used: "claude-opus-4-7",
    prompt_hash: "9e2a4b8c",
    response_hash: "1d3f5b7a",
    token_count: 18_402,
    latency_ms: 42_311,
    payload: { stages: 4, sub_agents: 9 },
  },
  {
    id: "audit-15",
    timestamp: "2026-04-06T09:02:24Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "pre_motion.stage.optimistic",
    module: "pre_motion",
    resource_type: "matter",
    resource_id: ID.matter,
    model_used: "claude-opus-4-7",
    prompt_hash: "ab12cd34",
    response_hash: "de56fg78",
    token_count: 2_104,
    latency_ms: 4_812,
    payload: { stage: "optimistic" },
  },
  {
    id: "audit-16",
    timestamp: "2026-04-06T09:02:41Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "pre_motion.stage.evidence",
    module: "pre_motion",
    resource_type: "matter",
    resource_id: ID.matter,
    model_used: "claude-opus-4-7",
    prompt_hash: "bc23de45",
    response_hash: "ef67gh89",
    token_count: 4_812,
    latency_ms: 11_204,
    payload: { stage: "evidence", sub_agents: 3 },
  },
  {
    id: "audit-17",
    timestamp: "2026-04-06T09:03:08Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "pre_motion.stage.premortem",
    module: "pre_motion",
    resource_type: "matter",
    resource_id: ID.matter,
    model_used: "claude-opus-4-7",
    prompt_hash: "cd34ef56",
    response_hash: "fg78hi90",
    token_count: 8_204,
    latency_ms: 18_402,
    payload: { stage: "premortem", sub_agents: 4 },
  },
  {
    id: "audit-18",
    timestamp: "2026-04-06T09:03:42Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "pre_motion.stage.synthesis",
    module: "pre_motion",
    resource_type: "matter",
    resource_id: ID.matter,
    model_used: "claude-opus-4-7",
    prompt_hash: "de45fg67",
    response_hash: "gh89ij01",
    token_count: 3_282,
    latency_ms: 7_893,
    payload: { stage: "synthesis" },
  },
  {
    id: "audit-19",
    timestamp: "2026-04-06T09:08:14Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "pre_motion.export.pdf",
    module: "pre_motion",
    resource_type: "matter",
    resource_id: ID.matter,
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 814,
    payload: { bytes: 184_213 },
  },
  {
    id: "audit-20",
    timestamp: "2026-04-06T10:42:18Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "contract_review.run",
    module: "contract_review",
    resource_type: "document",
    resource_id: ID.nda,
    model_used: "claude-opus-4-7",
    prompt_hash: "ef56gh78",
    response_hash: "ij01kl23",
    token_count: 12_104,
    latency_ms: 28_482,
    payload: { stages: 4, document: "synthetic-mutual-nda.docx" },
  },
  {
    id: "audit-21",
    timestamp: "2026-04-06T11:14:02Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "document.anonymise",
    module: "anonymisation",
    resource_type: "document",
    resource_id: ID.witness,
    model_used: "presidio",
    prompt_hash: null,
    response_hash: "kl23mn45",
    token_count: null,
    latency_ms: 1_204,
    payload: { engine: "presidio", entities: 8 },
  },
  {
    id: "audit-22",
    timestamp: "2026-04-06T11:18:55Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "review.create",
    module: "reviews",
    resource_type: "review",
    resource_id: ID.reviewCorrespondence,
    model_used: null,
    prompt_hash: null,
    response_hash: null,
    token_count: null,
    latency_ms: 48,
    payload: { title: "Acme correspondence — relevance" },
  },
  {
    id: "audit-23",
    timestamp: "2026-04-06T11:32:11Z",
    actor_id: ID.user,
    matter_id: ID.matter,
    action: "review.run",
    module: "reviews",
    resource_type: "review",
    resource_id: ID.reviewCorrespondence,
    model_used: "claude-opus-4-7",
    prompt_hash: "fg67hi89",
    response_hash: "mn45op67",
    token_count: 6_402,
    latency_ms: 9_812,
    payload: { cells_run: 24, cells_failed: 0 },
  },
];

const CHRONOLOGY: ChronologyResponse = {
  matter_slug: DEMO_SLUG,
  events: [
    {
      id: "ev-01",
      event_date: "2022-11-08",
      description: "Ms Khan begins continuous service at Acme Trading Ltd.",
      significance: 3,
      source_doc_ids: [],
      source_doc_filenames: [],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
    {
      id: "ev-02",
      event_date: "2026-01-29",
      description:
        "Ms Khan raises internal grievance re: line manager's conduct toward female warehouse staff.",
      significance: 4,
      source_doc_ids: [ID.witness],
      source_doc_filenames: ["witness-statement-khan.docx"],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
    {
      id: "ev-03",
      event_date: "2026-02-18",
      description:
        "Grievance acknowledged by HR; investigator appointed (same line manager subject of grievance).",
      significance: 3,
      source_doc_ids: [],
      source_doc_filenames: [],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
    {
      id: "ev-04",
      event_date: "2026-03-05",
      description:
        "Personal Instagram post made (private, audience 47, no customers / suppliers named).",
      significance: 3,
      source_doc_ids: [],
      source_doc_filenames: [],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
    {
      id: "ev-05",
      event_date: "2026-03-12",
      description: "Acme dismisses Ms Khan citing social-media policy breach. EDT.",
      significance: 5,
      source_doc_ids: [ID.dismissal],
      source_doc_filenames: ["khan-dismissal-letter.pdf"],
      priv_flag: false,
      from_disclosure: true,
      proceedings_refs: ["ET case 2406432/2026"],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
    {
      id: "ev-06",
      event_date: "2026-05-02",
      description: "ACAS Day A — EC notification submitted.",
      significance: 4,
      source_doc_ids: [],
      source_doc_filenames: [],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
    {
      id: "ev-07",
      event_date: "2026-05-24",
      description: "ACAS Day B — EC certificate issued.",
      significance: 4,
      source_doc_ids: [],
      source_doc_filenames: [],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
  ],
  gate: {
    required: true,
    confirmed: true,
    confirmed_at: "2026-04-04T13:02:14Z",
    tainted_event_count: 1,
  },
  statement_of_facts_variant: [
    {
      id: "ev-01",
      event_date: "2022-11-08",
      description: "Ms Khan begins continuous service at Acme Trading Ltd.",
      significance: 3,
      source_doc_ids: [],
      source_doc_filenames: [],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
    {
      id: "ev-02",
      event_date: "2026-01-29",
      description:
        "Claimant raised an internal grievance concerning her line manager's conduct.",
      significance: 4,
      source_doc_ids: [],
      source_doc_filenames: [],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
    {
      id: "ev-05",
      event_date: "2026-03-12",
      description: "Claimant was dismissed by the Respondent. EDT.",
      significance: 5,
      source_doc_ids: [],
      source_doc_filenames: [],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
    {
      id: "ev-06",
      event_date: "2026-05-02",
      description: "ACAS Day A — EC notification submitted.",
      significance: 4,
      source_doc_ids: [],
      source_doc_filenames: [],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
    {
      id: "ev-07",
      event_date: "2026-05-24",
      description: "ACAS Day B — EC certificate issued.",
      significance: 4,
      source_doc_ids: [],
      source_doc_filenames: [],
      priv_flag: false,
      from_disclosure: false,
      proceedings_refs: [],
      created_at: "2026-04-04T13:02:09Z",
      redacted: false,
    },
  ],
};

const ASSISTANT_MESSAGES: AssistantMessage[] = [
  {
    id: "asst-msg-01",
    role: "user",
    content: "summarise the NDA",
    suggested_actions: [],
    created_at: "2026-04-06T12:01:14Z",
  },
  {
    id: "asst-msg-02",
    role: "assistant",
    content:
      `This three-year mutual NDA [doc:${ID.nda}] between Acme Trading Ltd and North Mill Consulting Limited has three issues worth flagging. Confidentiality obligations survive indefinitely. The unlimited mutual indemnity is unlikely to be enforceable under UCTA s.3. The data-protection clause does not satisfy UK GDPR Art 28. And there is no governing law or jurisdiction clause.`,
    suggested_actions: [
      {
        type: "anonymise_document",
        label: "Anonymise this NDA",
        params: {},
      },
    ],
    created_at: "2026-04-06T12:01:18Z",
  },
  {
    id: "asst-msg-03",
    role: "user",
    content: "what was the dismissal date?",
    suggested_actions: [],
    created_at: "2026-04-06T12:02:41Z",
  },
  {
    id: "asst-msg-04",
    role: "assistant",
    content:
      "12 March 2026. Acme dismissed Ms Khan citing a social-media policy breach — see [chron:ev-05]. That date is the EDT for limitation purposes; ACAS Day A was filed on 2 May, so the s.207B extended ET1 deadline lands on 3 July 2026.",
    suggested_actions: [
      {
        type: "view_chronology",
        label: "Open the full chronology",
        params: {},
      },
    ],
    created_at: "2026-04-06T12:02:46Z",
  },
];

export const DEMO_SNAPSHOT = {
  matter: MATTER,
  documents: DOCUMENTS,
  audit: AUDIT,
  chronology: CHRONOLOGY,
  assistantMessages: ASSISTANT_MESSAGES,
};

export type DemoSnapshot = typeof DEMO_SNAPSHOT;
